In [5]:
import numpy
array = numpy.array([[11 ,22, 33], [44, 55, 66], [77, 88, 99]]) 
print("Printing 2D Array")
print(array)
print("Choose random row from 2D array")
randomRow = numpy.random.randint(3, size=2)
print('pickup', randomRow)
print(array[randomRow,:])

Printing 2D Array
[[11 22 33]
 [44 55 66]
 [77 88 99]]
Choose random row from 2D array
pickup [0 0]
[[11 22 33]
 [11 22 33]]
